"""empty message

Revision ID: 47079ea94020
Revises: 14f9b0a72563
Create Date: 2019-05-18 18:00:30.021282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "47079ea94020"
down_revision = "14f9b0a72563"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokengarbage",
        sa.Column("token_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("token", sa.String(length=255), nullable=False),
        sa.Column("dumped_on", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("token_id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=100), nullable=True),
        sa.Column("platform_admin", sa.Boolean(), nullable=False),
        sa.Column("user_registered_on", sa.DateTime(), nullable=False),
        sa.Column("user_quota", sa.Integer(), nullable=False),
        sa.Column("quota_remaining", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "resource",
        sa.Column("resource_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("resource_name", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.user_id"]),
        sa.PrimaryKeyConstraint("resource_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("resource")
    op.drop_table("user")
    op.drop_table("tokengarbage")
    # ### end Alembic commands ###
