"""empty message

Revision ID: 5e47ad284175
Revises: 788151ea56b5
Create Date: 2019-05-17 11:56:44.124530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e47ad284175'
down_revision = '788151ea56b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokengarbage',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('dumped_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token_id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokengarbage')
    # ### end Alembic commands ###
